apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}
  labels:
    app: ${app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}
  template:
    metadata:
      labels:
        app: ${app_name}
    spec:
      containers:
        - name: primary
          image: ${image}
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: ${app_name}-secret
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
      imagePullSecrets:
        - name: harbor-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ${app_name}
spec:
  selector:
    app: ${app_name}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ${app_name}
spec:
  rules:
    - host: $(ING_NAME)-${namespace}-kolpos.pea.co.th
      http:
        paths:
          - backend:
              service:
                name: ${app_name}
                port:
                  number: 80
            path: /
            pathType: Prefix
